- type: startingGear
  id: BunnySuitSmiteGear
  equipment:
    jumpsuit: ClothingCostumeBunnySuit
    id: CluwnePDA
    head: ClothingHeadHatBunnyHeadband
    ears: ClothingHeadsetService
    shoes: ClothingShoesHeels
