- type: latheRecipePack
  id: SecurityAmmoStaticOmu
  recipes:
  - MagazineShotgunLeverRifleEmpty
  - MagazineShotgunLeverRifle

- type: latheRecipePack
  id: SecurityVoidsuitsStaticOmu
  recipes:
  - UndeterminedVoidsuitSecurity