- type: latheRecipePack
  id: SecurityAmmoStaticOmu
  recipes:
  - MagazineShotgunLeverRifleEmpty
  - MagazineShotgunLeverRifle

- type: latheRecipePack
  id: SecurityWeaponsStaticOmu # This is the goob pack that was mald removed, bringing it back per bounty
  recipes:
  - PolymerBaton
  - SpearTelescopic
