- type: latheRecipePack
  id: SecurityAmmoStaticOmu
  recipes:
  - MagazineShotgunLeverRifleEmpty
  - MagazineShotgunLeverRifle

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxAntiTank
  result: MagazineBoxAntiTank
  materials:
    Steel: 1200
