// Portions taken from Monolith (https://github.com/monolith-station/monolith), credit tonotom1.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SmartFridge;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeItem : BoxContainer
{
    // Monolith start
    public Action? RemoveButtonPressed;
    // Monolith end

    public SmartFridgeItem(EntityUid uid, string text)
    {
        RobustXamlLoader.Load(this);

        EntityView.SetEntity(uid);
        NameLabel.Text = text;

        // Monolith start
        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke();

        if (uid.IsValid())
            RemoveButton.Visible = false;
        // Monolith end
    }
}
