using Content.Omu.Shared.Thaven;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Thaven;

[GenerateTypedNameReferences]
public sealed partial class MoodDisplay : Control
{
    private string GetSharedString()
    {
        return $"[italic][font size=10][color=gray]{Loc.GetString("moods-ui-shared-mood")}[/color][/font][/italic]";
    }

    public MoodDisplay(ThavenMood mood, bool shared)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (shared)
            MoodNameLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{mood.GetLocName()} {GetSharedString()}"));
        else
            MoodNameLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(mood.GetLocName()));

        MoodDescLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(mood.GetLocDesc()));
    }
}

